### ISSUE TITLE
"item" considered too generic in error messages

### ISSUE THREAD

**Issue by philrz** [brimdata/super#1137]
It has been noticed that when a file doesn't exist, `zq` now says `item does not exist`. An example of where this shows up is if I make a typo in a filename. This repro is with `zq` commit `2dfb278`.

```
$ zq -t 'foo' conns.log.gz 
conns.log.gz: item does not exist: file:///Users/phil/work/zq-sample-data/zeek-default/conns.log.gz
```

The consensus is that `item` is too generic a word. One proposal has been that we could drop the noun, such that the above would have been more like:

```
file:///Users/phil/work/zq-sample-data/zeek-default/conns.log.gz does not exist
```

**Comment by mccanne** [comment]
This has been fixed but the error message for file not sound is still a bit odd...
```
foo: file:///Users/mccanne/repo/zed/foo: file does not exist
```
I think we should just print the file the user typed on the command line.

Moving to backlog to close this out quickly...

**Comment by philrz** [comment]
Verified in super commit 9de86ad.

The error message has now been shortened to referenced just the name of the file the user typed on the command line.

```
$ super -version
Version: v1.18.0-99-g9de86ad2

$ super -z -c 'foo' conns.log.gz
conns.log.gz: file does not exist
```

Thanks @mccanne!
